version: '2'
services:
  mysql:
    environment:
     - TZ=Asia/Shanghai
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    hostname: mysql
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      secure_file_priv:
