admin:
    enable: true
    names:
        - admin
aes:
    key: "0123456789123456"
author: "zhouxiaolong 11688459@qq.com"
debug: true
jwt_diff: 604800
jwt_exp: 60
jwt_ref: 43200
jwt_secret: this1is2secret
ldap:
    basedn: dc=example,dc=org
    binddn: cn=admin,dc=example,dc=org
    bindpass: admin
    defaultpass: Xxxxx.ai@123
    host: vpnopenldap:389
    ldapattr:
        - myId
        - cn
        - sn
        - myLeader
        - myGoogle
        - myDep
        - myContactReg
        - myCompanyGroup
        - myPostion
        - myReg
        - myPhone
        - myTel
        - myEmail
        - myName
    userdn:
        signup: ou=tech
license: apache
mysql:
    addr: root:123456@tcp(vpnmysql:3306)/vpn?charset=utf8&&loc=Asia%2FShanghai
    idle: 10
    max: 20
netsarr:
    - eth0
pms:
    enable: false
    url: http://localhost:8081/user/name/%s/point/bool/%s
port: 29091
promethues:
    allin: irate(flow_out_total{instance='vpnapi:29091'}[1m])
    allout: irate(flow_in_total{instance='vpnapi:29091'}[1m])
    avg: vpn_avg1
    cpu: vpn_cpu_per
    mem: vpn_mem_per
    netbytes:
        down: irate(vpn_netin{device='eth0',instance='vpnapi:29091'}[1m])
        upload: irate(vpn_netout{device='eth0',instance='vpnapi:29091'}[1m])
    query: http://vpnprometheus:9090/api/v1/query
    queryrange: http://vpnprometheus:9090/api/v1/query_range
    timeout: 5s
    users: vpn_users
